### ISSUE TITLE
Custom tab bar image with corner radius

### ISSUE THREAD

**Issue by escully27** [Minitour/AZTabBarController#24]
Hey!

Trying to set a custom image for the 4th index like so... 

`        tabController.setButtonImage(forIndex: 4, normal: UIImage(data: data!)!, selected: UIImage(data: data!)!)
`

and it is successfully putting the correct image there, but I was wondering how to change the button's frame (so it doesn't take up the entire index, but fit something like w: 23, h: 23) and also be a circle with a corner radius on the image. 

tried this, but it isn't working
`private func createButton(forIndex index:Int)-> UIButton{
        let button = AZTabBarButton(type: .custom)
        button.delegate = self
        button.tag = index
        button.isExclusiveTouch = true
        button.imageView?.contentMode = .scaleAspectFit
        
        if index == 4 {
            button.imageView?.contentMode = .scaleAspectFill
            button.imageView?.layer.cornerRadius = button.frame.width / 2
        }
        
        button.addTarget(self, action: #selector(self.tabButtonAction(button:)), for: .touchUpInside)
     //   button.frame = CGRect(x: 0, y: 0, width: 23, height: 23)
        return button
    }`

**Comment by Minitour** [comment]
@escully27 Hi, The buttons inside the container will have a fixed frame due to the constraints that are set by the UIStackView, therefore their size cannot be changed. (in terms of frame).

The UIImageView is still nil at the point which you were setting a corner radius which is why it didn't work.

I would recommend checking out issue #11, in which I explain in detail how to customize the tab bar.

I would also recommend trying to round the UIImage itself and then setting it on the button. 
Checkout this [answer](https://stackoverflow.com/a/29046647/5664330) on Stack Overflow.
