### ISSUE TITLE
highlightColor does not change color of tab title text

### ISSUE THREAD

**Issue by ProbablyFaiz** [Minitour/AZTabBarController#41]
![screen shot 2018-08-13 at 1 24 47 pm](https://user-images.githubusercontent.com/34611522/44056177-4e585d80-9efc-11e8-9d51-4d77584e6284.png)

In this case, my highlighted tab uses an inverted color scheme compared to the other tabs. To do this, I changed `highlightColor` to the light blue color you see in the picture. However, this does not change the title text of that tab, so it still displays light blue and therefore does not show up.

**Comment by Faiz-Surani** [comment]
Update: I was able to implement at least a patchwork fix by adding this to the end of the for loop in the `customizeButtons` method that is located in AZTabBarController.swift:
`if (isHighlighted) {
                button.setTitleColor(highlightColor, for: [])
            }`

The issue is still worth fixing, but I'll leave this here in case anyone is having a similar issue in the interim.
